apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ah3w
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-ah3w@sha256:01390858ddff7eabd3268efd0e61e36bdde84d9f6493b26f6da29d73e6567865
        name: my-nodejs
        resources: {}
status: {}
